[project]
name = "crawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "bs4>=0.0.2",
    "crawl4ai>=0.7.4",
    "tldextract>=5.3.0",
]
